
# Generated by Django 4.2.1 on 2023-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Book title')),
                ('author', models.CharField(max_length=255, verbose_name='Book title')),
                ('description', models.TextField(verbose_name='Book Description')),
                ('likes', models.IntegerField(default=0)),
                ('watch_count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('rate', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
