# Generated by Django 4.2.1 on 2023-06-01 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster_image',
        ),
        migrations.RemoveField(
            model_name='series',
            name='poster_image',
        ),
    ]
